read.csv("data/raw/teaching_training_data.csv")
read.csv("data/raw/teaching_training_data_cft.csv")
read.csv("data/raw/teaching_training_data_com.csv")
read.csv("data/raw/teaching_training_data_grit.csv")
read.csv("data/raw/teaching_training_data_num.csv")
read.csv("data/raw/teaching_training_data_opt.csv")